export interface WorkableCompany {
  slug: string
  name: string
}

export const WORKABLE_COMPANIES: WorkableCompany[] = [
  { slug: 'skroutz', name: 'Skroutz' },
  { slug: 'efood', name: 'e-food' },
  { slug: 'blueground', name: 'Blueground' },
  { slug: 'viva-wallet', name: 'Viva Wallet' },
  { slug: 'beat', name: 'Beat' },
  { slug: 'taxibeat', name: 'TaxiBeat' },
  { slug: 'softone', name: 'Softone' },
  { slug: 'entersoft', name: 'Entersoft' },
  { slug: 'intrasoft', name: 'Intrasoft' },
  { slug: 'singular-logic', name: 'Singular Logic' },
  { slug: 'upstream', name: 'Upstream' },
  { slug: 'netcompany-intrasoft', name: 'Netcompany-Intrasoft' },
  { slug: 'eurobank', name: 'Eurobank' },
  { slug: 'nbg', name: 'NBG' },
  { slug: 'piraeusbank', name: 'Piraeus Bank' },
  { slug: 'alphabank', name: 'Alpha Bank' },
  { slug: 'opap', name: 'OPAP' },
  { slug: 'jumbo-sa', name: 'Jumbo' },
  { slug: 'public-gr', name: 'Public' },
  { slug: 'kotsovolos', name: 'Kotsovolos' },
  { slug: 'plaisio', name: 'Plaisio' },
  { slug: 'wolt-greece', name: 'Wolt' },
  { slug: 'delivery-hero-greece', name: 'Delivery Hero' },
  { slug: 'booking-holdings', name: 'Booking Holdings' },
  { slug: 'trivago-greece', name: 'Trivago' },
  { slug: 'adidas-greece', name: 'Adidas' },
  { slug: 'ikea-greece', name: 'IKEA' },
  { slug: 'lidl-greece', name: 'Lidl' },
  { slug: 'ab-vassilopoulos', name: 'AB Βασιλόπουλος' },
  { slug: 'fourlis', name: 'Fourlis' },
  { slug: 'mytilineos', name: 'Mytilineos' },
  { slug: 'motor-oil', name: 'Motor Oil' },
  { slug: 'hellenic-petroleum', name: 'Hellenic Petroleum' },
  { slug: 'cosmote', name: 'Cosmote' },
  { slug: 'wind-hellas', name: 'Wind Hellas' },
  { slug: 'nova-greece', name: 'Nova' },
  { slug: 'forthnet', name: 'Forthnet' },
]
